In [7]:
import numpy as np
import pandas as pd
def e_distance(a,b):
    ans=0
    for i in range(len(a)):
        ans+=np.abs(a[i]-b[i])**2
    return np.sqrt(ans)
def init(k_num,x_dim):
    middle=np.random.randint(size=(k_num,x_dim),low=1,high=15,dtype=int)
    return middle

In [8]:
init_middle=init(26,16)

In [9]:
init_middle.astype(float)
#init_middle=[]

array([[ 2.,  6.,  3.,  1.,  6.,  8., 11.,  6., 13., 14.,  8., 10., 11.,
        14.,  5.,  7.],
       [ 6.,  5.,  1., 11.,  4., 11.,  2., 10., 11., 11.,  7.,  4., 13.,
        11.,  4.,  2.],
       [ 9.,  6.,  9., 14.,  4.,  5., 13., 13.,  7.,  5.,  8.,  4.,  7.,
         5., 12., 11.],
       [ 9.,  2., 12.,  6.,  7.,  2., 14., 13.,  7.,  4.,  5.,  2.,  8.,
         1.,  5., 12.],
       [ 5., 13., 12., 13.,  6.,  6., 14.,  2., 11., 13.,  3.,  3.,  1.,
        13., 11., 11.],
       [ 4.,  3., 10.,  1.,  5.,  2., 14.,  7.,  3.,  7., 13.,  9.,  6.,
         7.,  5.,  1.],
       [13., 13.,  5.,  3.,  6.,  9.,  1.,  8., 14.,  7.,  3.,  1.,  8.,
         2.,  9.,  9.],
       [ 1., 13., 10.,  7., 11.,  2.,  4.,  7.,  8.,  1.,  4.,  3.,  2.,
        10., 10.,  5.],
       [11., 13., 14., 11.,  7.,  4.,  5., 10.,  5., 10.,  6.,  1.,  6.,
         5., 12.,  4.],
       [12.,  5.,  7., 11., 14.,  6.,  7.,  2., 13.,  8.,  6., 10.,  8.,
         9.,  6.,  5.],
       [ 1.,  3., 13.,  6., 14

In [10]:
#data load
import scipy.io as scio
letter_data = scio.loadmat('./data/le1.mat')
letter_msg=letter_data['data']
letter_msg=letter_msg.astype(float)
letter_label=letter_data['label']
def min_dis(data_X,middle):
    min_num=1000000
    min_index=0
    for i in range(len(middle)):
        if min_num>e_distance(data_X,middle[i]):
            min_num=e_distance(data_X,middle[i])
            min_index=i
    return min_index
init_middle=[]
init_middle.append(letter_msg[0])#20
init_middle.append(letter_msg[1])#9 
init_middle.append(letter_msg[2])#4
init_middle.append(letter_msg[3])#14
init_middle.append(letter_msg[4])#7
init_middle.append(letter_msg[5])#19
init_middle.append(letter_msg[6])#2
init_middle.append(letter_msg[7])#1
init_middle.append(letter_msg[8])#10
init_middle.append(letter_msg[9])#13
init_middle.append(letter_msg[10])#24
init_middle.append(letter_msg[11])#15
init_middle.append(letter_msg[39])#5
init_middle.append(letter_msg[107])#11
init_middle.append(letter_msg[14])#18
init_middle.append(letter_msg[15])#6
init_middle.append(letter_msg[59])#12
init_middle.append(letter_msg[17])#3
init_middle.append(letter_msg[37])#16
init_middle.append(letter_msg[55])#17
init_middle.append(letter_msg[99])#21
init_middle.append(letter_msg[21])#8
init_middle.append(letter_msg[44])#22
init_middle.append(letter_msg[27])#23
init_middle.append(letter_msg[50])#25
init_middle.append(letter_msg[151])#26
letter_msg

array([[ 2.,  8.,  3., ...,  8.,  0.,  8.],
       [ 5., 12.,  3., ...,  8.,  4., 10.],
       [ 4., 11.,  6., ...,  7.,  3.,  9.],
       ...,
       [ 6.,  9.,  6., ..., 12.,  2.,  4.],
       [ 2.,  3.,  4., ...,  9.,  5.,  8.],
       [ 4.,  9.,  6., ...,  7.,  2.,  8.]])

In [11]:
def recal(middle,index_num,data):
    for i in range(len(middle)):
        cla_num=len(index_num[i])
        if cla_num==0:
            continue
        sum_vec=np.zeros(16)
        for j in range(len(index_num[i])):
            sum_vec+=data[index_num[i][j]]
        middle[i]=(sum_vec)/cla_num
        #print(middle[i])
    return middle

In [15]:
#apply k means
epoch=30
classfi=[]
for i in range(26):
    classfi.append([])
for i in range(50):
    classfi=[]
    for i in range(26):
        classfi.append([])
    for j in range(len(letter_msg)):
        classfi[min_dis(letter_msg[j],init_middle)].append(j)
    init_middle=recal(init_middle,classfi,letter_msg)


In [17]:
count=0
middle_label=[20,9,4,14,7,19,2,1,10,13,24,15,5,11,18,6,12,3,16,17,21,8,22,23,25,26]
real=[]
p=0
for i in range(26):
    num=np.zeros(26).astype(int)
    for j in range(len(classfi[i])):
        num[letter_label[classfi[i][j]]-1]+=1
    print(num)
    real.append(np.argmax(num)+1)
    p+=num[np.argmax(num)]
            
real
for i in range(26):
    for j in range(len(classfi[i])):
        if letter_label[classfi[i][j]]==real[i]:
            count+=1
p
k_res=np.zeros(20000)
for i in range(26):
    for j in range(len(classfi[i])):
        k_res[classfi[i][j]]+=i

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0 120  21 136  48   0 141   0]
[ 10   0   0   1   0   0   0   0   0 202   0   1   1   0   0   0   0   0
   0   0   0   0   0   0   0   0]
[  6 117   0 143  54  32   6  66  43  42  77   3  36  59  10  30  21 122
  66   0   0   0   0  55   0  51]
[  0   0   0   0   0   0   0   0   0   0   0 329   0   0   0   0   0   0
   0   0   0   0   0   0   0   0]
[  0   6   0  44   0   0   2  45  72   0  35   0  77  91 110  40 111  46
   0   0  59   0  43  29   0   0]
[  0  23   0   0  37   0   8   0   0   0   0   0   0   0   0   0   3   0
 165   8   0   0   0  89   0 258]
[  0 108 105  43  97   0 169  46   7   0  58   0   0   0  19   0  24  58
  80   0  17   0   0  93   0 106]
[249   0   0   0   0   0   0   0   0  31   0   4   0   0   0   0   0   0
   0   0   0   0   0   0   0   1]
[  0  88   1 104  85  18   0  59 227 159  55  89   5  30   1  37   0  66
  70   0   0   0   0  53   0  66]
[73 25  6 29  6  1 14  3 28  3  7 53 

In [18]:
k_res=np.zeros(20000)
for i in range(len(classfi)):
    for j in range(len(classfi[i])):
        k_res[classfi[i][j]]+=i
k_res

array([22.,  9.,  2., ..., 20.,  8., 16.])

In [19]:
#外部指标计算
a=0
b=0
c=0
d=0
for i in range(20000):
    for j in range(20000):
        if letter_label[i]==letter_label[j]:
            if k_res[i]==k_res[j]:
                a+=1
            else:
                b+=1
        else:
            if k_res[i]==k_res[j]:
                c+=1
            else:
                d+=1
print('{}.{}.{}.{}'.format(a,b,c,d))

2699518.12698524.15744362.368857596


In [20]:
JC=a/(a+b+c)
JC

0.08668303192007913

In [21]:
FMI=np.sqrt((a/(a+b))*(a/(a+c)))
FMI

0.16018702426025427

In [22]:
RI=((a+d))/(a+b+c+d)
RI

0.928892785

In [23]:
#内部度量 init_middle储存中心点信息
avg=[]
for i in range(26):
    sum_d=0
    max_d=0
    for j in range(len(classfi[i])):
        for p in range(len(classfi[i])):
            dist=e_distance(letter_msg[classfi[i][p]],letter_msg[classfi[i][j]])
            if dist>max_d:
                max_d=dist
            sum_d+=dist
    avg.append(sum_d/((len(classfi[i])-1)*len(classfi[i])))
avg

[6.527024887328189,
 7.878055373477884,
 7.32566556929274,
 7.952726153597628,
 7.245982388627218,
 7.089305685868965,
 6.496838246676265,
 6.354826582120335,
 6.920357443587514,
 8.773145312440667,
 7.721464238601552,
 7.955792263449751,
 6.875399501205076,
 7.778520627397136,
 7.235476033475897,
 7.449524414548746,
 7.611505847097344,
 7.242065132236902,
 7.078356736088345,
 7.399653914475078,
 7.55837934790766,
 7.965223820475485,
 7.282967384459448,
 9.56989199557527,
 8.795397060370018,
 8.590700782044824]

In [24]:
inertia=0
for i in range(26):
    for j in range(len(classfi[i])):
        inertia+=e_distance(letter_msg[classfi[i][j]],init_middle[i])
inertia

107324.17735601003

In [25]:
DBI=0
for i in range(26):
    max_in=0
    for j in range(26):
        if i==j:
             continue
        else:
            if (avg[i]+avg[j])/e_distance(init_middle[i],init_middle[j])>max_in:
                max_in=(avg[i]+avg[j])/e_distance(init_middle[i],init_middle[j])
    DBI+=max_in
DBI=DBI/26
DBI

2.302006682123014